{   
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"InternetSales\",\"Product\",\"PresupuestoCompras\",\"ProductCategory\",\"ProductSubCategory\",\"Customer\",\"Stores\",\"TablaFecha\",\"Cambiador_unidades\",\"TableTypes\",\"ReduccionFilas\",\"TableRLS\",\"UserByPage\",\"TableCountConsecutive\",\"Diagnostics_Counters_2021-09-02_20:26\",\"Diagnostics_Detailed_2021-09-02_20:26\",\"Diagnostics_Aggregated_2021-09-02_20:26\",\"Diagnostics_Partitions_2021-09-02_20:26\",\"TooltipDocs\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "ReduccionFilas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2005, 12, 31) meta [IsParameterQuery=true, Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "467e6609-00e8-4bc2-afd8-507fbbd1429d",
        "queryGroup": "Parameters"
      },
      {
        "name": "Diagnostics_Counters_2021-09-02_20:26",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    TransformCsv = (filecontents as binary) => [",
          "        Source = Csv.Document(filecontents,[Delimiter=\",\", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        result = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    ][result],",
          "    CsvFiles = #table(type table[Id = text, File = text], {",
          "        {\"1.1\", \"C:\\Users\\IBARRAU\\AppData\\Local\\Microsoft\\Power BI Desktop\\Traces\\Diagnostics\\EvaluationCounters_20210902T202614.026-c4e92b85-aae3-4c27-9635-8545353982a9-1-001.csv\"}",
          "    }),",
          "    GetContents = Table.AddColumn(CsvFiles, \"Content\", each File.Contents([File])),",
          "    AddColumn = Table.AddColumn(GetContents, \"Transform File\", each TransformCsv([Content])),",
          "    ExpandedTransformFile = Table.ExpandTableColumn(AddColumn, \"Transform File\", ",
          "                { \"Timestamp\", \"Processor Time (%)\", \"Total Processor Time\", \"IO Data Bytes Per Second\", \"Commit (bytes)\", \"Working Set (bytes)\" },",
          "                { \"Timestamp\", \"Processor Time (%)\", \"Total Processor Time\", \"IO Data Bytes Per Second\", \"Commit (bytes)\", \"Working Set (bytes)\" }),",
          "    TransformedColumns = Table.TransformColumnTypes(ExpandedTransformFile,",
          "        {{\"Timestamp\", type datetime}, {\"Processor Time (%)\", Percentage.Type}, {\"Total Processor Time\", type duration}, {\"IO Data Bytes Per Second\", type number}, {\"Commit (bytes)\", Int64.Type}, {\"Working Set (bytes)\", Int64.Type}}),",
          "    RemovedColumns = Table.RemoveColumns(TransformedColumns, {\"File\", \"Content\"})",
          "in",
          "    RemovedColumns"
        ],
        "kind": "m",
        "lineageTag": "d7b57360-a2d5-49c0-b15e-1686f56499c7",
        "queryGroup": "Diagnostics"
      },
      {
        "name": "Diagnostics_Detailed_2021-09-02_20:26",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Json.Document(File.Contents(\"C:\\Users\\IBARRAU\\AppData\\Local\\Microsoft\\Power BI Desktop\\Traces\\Diagnostics\\Diagnostics_Detailed_20210902T202615.250-17a24534-e669-496d-83b4-234fac6ef3c0.json\")),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\",",
          "        {\"Id\", \"Query\", \"Step\", \"Category\", \"DataSourceKind\", \"Operation\", \"StartTime\", \"EndTime\", \"ExclusiveDurationPct\", \"ExclusiveDuration\", \"Resource\", \"DataSourceQuery\", \"AdditionalInfo\", \"RowCount\", \"ContentLength\", \"IsUserQuery\", \"Path\", \"GroupId\", \"PartitionKey\", \"Process\", \"ActivityId\", \"DataSourceOperationIds\"},",
          "        {\"Id\", \"Query\", \"Step\", \"Category\", \"Data Source Kind\", \"Operation\", \"Start Time\", \"End Time\", \"Exclusive Duration (%)\", \"Exclusive Duration\", \"Resource\", \"Data Source Query\", \"Additional Info\", \"Row Count\", \"Content Length\", \"Is User Query\", \"Path\", \"Group Id\", \"Partition Key\", \"Process\", \"Activity Id\", \"Data Source Operation Identifiers\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\", ",
          "        {{\"Id\", type text}, {\"Query\", type text}, {\"Step\", type text}, {\"Category\", type text}, {\"Data Source Kind\", type text}, {\"Operation\", type text}, {\"Start Time\", type datetime}, {\"End Time\", type datetime}, {\"Exclusive Duration (%)\", Percentage.Type}, {\"Exclusive Duration\", type duration}, {\"Resource\", type text}, {\"Data Source Query\", type text}, {\"Additional Info\", type any}, {\"Row Count\", Int64.Type}, {\"Content Length\", Int64.Type}, {\"Is User Query\", type logical}, {\"Path\", type text}, {\"Group Id\", type number}, {\"Partition Key\", type text}, {\"Process\", type text}, {\"Activity Id\", type text}, {\"Data Source Operation Identifiers\", type any}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "0f75257f-cff8-4c23-a64c-74a7991c334d",
        "queryGroup": "Diagnostics"
      },
      {
        "name": "Diagnostics_Aggregated_2021-09-02_20:26",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Json.Document(File.Contents(\"C:\\Users\\IBARRAU\\AppData\\Local\\Microsoft\\Power BI Desktop\\Traces\\Diagnostics\\Diagnostics_Aggregated_20210902T202615.250-17a24534-e669-496d-83b4-234fac6ef3c0.json\")),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\",",
          "        {\"Id\", \"Query\", \"Step\", \"Category\", \"DataSourceKind\", \"Operation\", \"StartTime\", \"EndTime\", \"ExclusiveDurationPct\", \"ExclusiveDuration\", \"Resource\", \"DataSourceQuery\", \"AdditionalInfo\", \"RowCount\", \"ContentLength\", \"IsUserQuery\", \"Path\", \"GroupId\", \"PartitionKey\"},",
          "        {\"Id\", \"Query\", \"Step\", \"Category\", \"Data Source Kind\", \"Operation\", \"Start Time\", \"End Time\", \"Exclusive Duration (%)\", \"Exclusive Duration\", \"Resource\", \"Data Source Query\", \"Additional Info\", \"Row Count\", \"Content Length\", \"Is User Query\", \"Path\", \"Group Id\", \"Partition Key\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\", ",
          "        {{\"Id\", type text}, {\"Query\", type text}, {\"Step\", type text}, {\"Category\", type text}, {\"Data Source Kind\", type text}, {\"Operation\", type text}, {\"Start Time\", type datetime}, {\"End Time\", type datetime}, {\"Exclusive Duration (%)\", Percentage.Type}, {\"Exclusive Duration\", type duration}, {\"Resource\", type text}, {\"Data Source Query\", type text}, {\"Additional Info\", type any}, {\"Row Count\", Int64.Type}, {\"Content Length\", Int64.Type}, {\"Is User Query\", type logical}, {\"Path\", type text}, {\"Group Id\", type number}, {\"Partition Key\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "5e55c6ea-4116-4be6-83db-3a5fe9b6d0cc",
        "queryGroup": "Diagnostics"
      },
      {
        "name": "Diagnostics_Partitions_2021-09-02_20:26",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Json.Document(File.Contents(\"C:\\Users\\IBARRAU\\AppData\\Local\\Microsoft\\Power BI Desktop\\Traces\\Diagnostics\\Diagnostics_Partitions_20210902T202615.250-17a24534-e669-496d-83b4-234fac6ef3c0.json\")),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\",",
          "        {\"Id\", \"PartitionKey\", \"FirewallGroup\", \"AccessedResources\", \"PartitionInputs\", \"Expression\", \"StartTime\", \"EndTime\", \"Duration\", \"ExclusiveDuration\", \"ExclusiveDurationPct\"},",
          "        {\"Id\", \"Partition Key\", \"Firewall Group\", \"Accessed Resources\", \"Partition Inputs\", \"Expression\", \"Start Time\", \"End Time\", \"Duration\", \"Exclusive Duration\", \"Exclusive Duration (%)\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\", ",
          "        {{\"Id\", type text}, {\"Partition Key\", type text}, {\"Firewall Group\", type text}, {\"Accessed Resources\", type any}, {\"Partition Inputs\", type any}, {\"Expression\", type text}, {\"Start Time\", type datetime}, {\"End Time\", type datetime}, {\"Duration\", type duration}, {\"Exclusive Duration\", type duration}, {\"Exclusive Duration (%)\", Percentage.Type}}),",
          "    AddPartitionId = (targetTable as table) => Table.AddColumn(targetTable, \"PartitionId\", each Text.Combine({[Id], \".\", [Partition Key]}), type text),",
          "    RemovePartitionId = (column as any) => if column is table then Table.RemoveColumns(column, {\"PartitionId\"}) else column,",
          "    AddedDiagnosticsColumn = Table.NestedJoin(AddPartitionId(#\"Changed Type\"), {\"PartitionId\"}, AddPartitionId(#\"Diagnostics_Detailed_2021-09-02_20:26\"), {\"PartitionId\"}, \"Diagnostics\", JoinKind.LeftOuter),",
          "    RemovedPartitionIdOnDiagnostics = Table.TransformColumns(AddedDiagnosticsColumn, {\"Diagnostics\", RemovePartitionId}, null, MissingField.UseNull),",
          "    RemovedPartitionId = RemovePartitionId(RemovedPartitionIdOnDiagnostics)",
          "in",
          "    RemovedPartitionId"
        ],
        "kind": "m",
        "lineageTag": "89dbba49-afad-44f5-984e-db612002cb10",
        "queryGroup": "Diagnostics"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Facts"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Dimensions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Auxiliars"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "description": "Query group for diagnostics",
        "folder": "Diagnostics"
      }
    ],
    "relationships": [
      {
        "name": "7d857fff-e287-44f2-9eb7-56beb9e1fb99",
        "fromColumn": "ProductKey",
        "fromTable": "InternetSales",
        "toColumn": "ProductKey",
        "toTable": "Product"
      },
      {
        "name": "ed7b296a-94cf-4dcd-a60f-ae5b018b0f54",
        "fromColumn": "CustomerKey",
        "fromTable": "InternetSales",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "65cbe522-f1a2-44dd-8a66-7bd67b66b99e",
        "fromColumn": "ProductSubcategoryKey",
        "fromTable": "Product",
        "toColumn": "ProductSubcategoryKey",
        "toTable": "ProductSubCategory"
      },
      {
        "name": "b24f5a62-f981-4d3a-a256-74962dde9354",
        "fromColumn": "ProductCategoryKey",
        "fromTable": "ProductSubCategory",
        "toColumn": "ProductCategoryKey",
        "toTable": "ProductCategory"
      },
      {
        "name": "eed5c566-041f-445e-90dc-9673fa36a617",
        "fromColumn": "Order Date",
        "fromTable": "InternetSales",
        "toColumn": "Fecha",
        "toTable": "TablaFecha"
      },
      {
        "name": "6e0c2254-d25e-4a54-a64f-3bec2956b1e0",
        "fromColumn": "StoreKey",
        "fromTable": "InternetSales",
        "toColumn": "StoreKey",
        "toTable": "Stores"
      },
      {
        "name": "b90f12b6-e50e-4cc5-92cc-34e9de52cc75",
        "fromColumn": "CountryRegion",
        "fromTable": "Stores",
        "toCardinality": "many",
        "toColumn": "Country",
        "toTable": "TableRLS"
      },
      {
        "name": "3950c1d8-b269-4086-ad4f-00017751a29d",
        "fromColumn": "Fecha",
        "fromTable": "TableCountConsecutive",
        "toColumn": "Fecha",
        "toTable": "TablaFecha"
      }
    ],
    "roles": [
      {
        "name": "Sucursal China",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fbbe6a1c0efe46febd7a464d903f7e7c"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Stores",
            "filterExpression": "[CountryRegion] = \"China\""
          }
        ]
      },
      {
        "name": "VerTodo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "27a246cf30834d1ba42c0d34a8e90757"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "Dynamic",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "db7a546a0ff04193ad6da8776a30fa63"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "TableRLS",
            "filterExpression": "[Mail] = USERNAME()"
          }
        ]
      },
      {
        "name": "RLS-Pagina",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8cd0a004893b4190a4fea88ea294cf0a"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "UserByPage",
            "filterExpression": "[UserConnected] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "es-AR",
    "tables": [
      {
        "name": "Cambiador_unidades",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Unidades",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09ac8477-f706-4ee3-a130-039963d345c3",
            "sourceColumn": "Unidades",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5a47fb28-d146-4dad-8363-16bcad2670b3",
        "partitions": [
          {
            "name": "Cambiador_unidades-ecc2587e-3447-4819-9283-469a5f22b025",
            "mode": "import",
            "queryGroup": "Auxiliars",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8s3MSS1WitUBs3Ly86Cc4Mw8haLU4tLczCKl2FgA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Unidades = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Unidades\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Birth Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "df2c4fc5-cf4d-44b8-a67f-9eee1d603ca1",
            "sourceColumn": "Birth Date",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b87a2602-2cb1-40ac-a0e3-ab83d2b0638d",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7d5f887-ec1e-48e8-915e-f7bd453597cf",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "CountryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba8c96a3-7a6a-454e-aed1-c0e67f88f4a0",
            "sourceColumn": "CountryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f951ec9e-92b8-43df-a8d4-3bf3354d4bf1",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Education",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c355305-297a-445b-ab8d-295a8d7e8be2",
            "sourceColumn": "Education",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd95c709-a406-4eea-ad81-d0fadb1cec14",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Marital Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a3ccd92-f155-4b7d-b95b-4a8cd2f5304e",
            "sourceColumn": "Marital Status",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7345f632-f2d3-4d4f-aabf-4ec49c906af8",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80365f2e-b71c-493f-853c-1c05ada57cc0",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5a54db3-7085-4508-97c0-9a46ea3754ce",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7a5f1ba2-988f-47a7-96f9-928a74e2a31e",
        "measures": [
          {
            "name": "Ultima Compra a la fecha seleccionada",
            "expression": [
              "",
              "Var SelDate = SELECTEDVALUE(TablaFecha[Fecha])",
              "Var wtf = ",
              "CALCULATE (",
              "    MAX(InternetSales[Order Date])",
              "    ,FILTER(Customer, INT(NOT ISEMPTY(InternetSales)) = 1)",
              "    --,FILTER(ALLEXCEPT(InternetSales, Customer[CustomerKey]), InternetSales[Order Date]<SelDate )",
              "    ,FILTER(ALL(TablaFecha), TablaFecha[Fecha]<SelDate )",
              ")",
              "RETURN wtf // por que le puse ese nombre al a var"
            ],
            "formatString": "General Date",
            "lineageTag": "e388d463-0c48-4f92-8dee-f37625c9ce30"
          },
          {
            "name": "Hace 200 dias que no compran",
            "expression": [
              "",
              "var __select = SELECTEDVALUE(TablaFecha[Fecha])",
              "RETURN",
              "COUNTROWS ( ",
              "    FILTER ( ",
              "        ADDCOLUMNS(",
              "            VALUES(Customer[CustomerKey])",
              "            , \"@dif\", [Dias sin comprar]",
              "         ), [@dif] > 200",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ab6ad0bc-5934-440d-88ec-5bb604f03bfb"
          },
          {
            "name": "Dias sin comprar",
            "expression": [
              "",
              "VAR __select = SELECTEDVALUE(TablaFecha[Fecha])",
              "RETURN",
              "DATEDIFF([Ultima Compra a la fecha seleccionada], __select, DAY)"
            ],
            "formatString": "0",
            "lineageTag": "c42289cb-d03a-4f33-aac0-f3a35c425df5"
          }
        ],
        "partitions": [
          {
            "name": "Customer-20617443-d600-4c17-a372-0c1f031c4fe2",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/Customer.csv\"),[Delimiter=\";\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"CustomerKey\", Int64.Type}, {\"Name\", type text}, {\"Marital Status\", type text}, {\"Gender\", type text}, {\"Education\", type text}, {\"Occupation\", type text}, {\"Continent\", type text}, {\"City\", type text}, {\"State\", type text}, {\"CountryRegion\", type text}, {\"Birth Date\", type datetime}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "InternetSales",
        "annotations": [
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":11,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/InternetSales/Tipo cambiado.{StoreKey,0}\",\"Section1/InternetSales/Tipo cambiado.{ProductKey,1}\",\"Section1/InternetSales/Tipo cambiado.{CustomerKey,2}\",\"Section1/InternetSales/Tipo cambiado.{Quantity,3}\",\"Section1/InternetSales/Tipo cambiado.{Unit Price,4}\",\"Section1/InternetSales/Tipo cambiado.{Unit Discount,5}\",\"Section1/InternetSales/Tipo cambiado.{Unit Cost,6}\",\"Section1/InternetSales/Tipo cambiado.{Net Price,7}\",\"Section1/InternetSales/Tipo cambiado.{Order Date,8}\",\"Section1/InternetSales/Tipo cambiado.{Due Date,9}\",\"Section1/InternetSales/Tipo cambiado.{Delivery Date,10}\"],\"ColumnCount\":11,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/InternetSales/Tipo cambiado.{StoreKey,0}\",\"Section1/InternetSales/Tipo cambiado.{ProductKey,1}\",\"Section1/InternetSales/Tipo cambiado.{CustomerKey,2}\",\"Section1/InternetSales/Tipo cambiado.{Quantity,3}\",\"Section1/InternetSales/Tipo cambiado.{Unit Price,4}\",\"Section1/InternetSales/Tipo cambiado.{Unit Discount,5}\",\"Section1/InternetSales/Tipo cambiado.{Unit Cost,6}\",\"Section1/InternetSales/Tipo cambiado.{Net Price,7}\",\"Section1/InternetSales/Tipo cambiado.{Order Date,8}\",\"Section1/InternetSales/Tipo cambiado.{Due Date,9}\",\"Section1/InternetSales/Tipo cambiado.{Delivery Date,10}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d07766d-3a69-45ec-9b40-9183236a1f23",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d1a2e274-2c7e-4980-b769-a7d089bd2752",
            "sourceColumn": "Delivery Date",
            "summarizeBy": "none"
          },
          {
            "name": "Due Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "84bc699f-872d-44e2-b318-3f5475296cb2",
            "sourceColumn": "Due Date",
            "summarizeBy": "none"
          },
          {
            "name": "Net Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "aca3ca3c-d515-4836-bec3-e704bf0acd00",
            "sourceColumn": "Net Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Nombre del Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Columna relacionada de la tabla producto en la fact de ventas",
            "expression": "RELATED('Product'[Product Name])",
            "isDataTypeInferred": true,
            "lineageTag": "ef8d3486-9ce2-4783-aed2-ebdb838d2801",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Order Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f2ba9b27-259d-457b-9a0b-74418f00bb95",
            "sourceColumn": "Order Date",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c65e8cac-b36b-494a-a2de-0d1411b07b0b",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23ad2e14-3804-449e-86fe-dc910de5f21e",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "211e88d7-e36a-4cce-8236-44503d4c7deb",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "68981af0-d46f-4b15-8dc9-b0357b9af105",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "588777ef-9655-47d1-befd-f8f88122afc7",
            "sourceColumn": "Unit Discount",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "66fec939-240b-406f-8865-f11142f88a78",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6e682e57-cfa4-40da-8460-c66cc624502a",
        "measures": [
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR _Units = SELECTEDVALUE(Cambiador_unidades[Unidades], \"Sin resumir\")",
              "RETURN",
              "SWITCH(_Units, \"Millones\", 0.000001, \"Miles\", 0.001, 1)",
              "*",
              "SUMX(",
              "    InternetSales,  ",
              "    InternetSales[Net Price]*InternetSales[Quantity] ",
              ") ",
              "* [Valor Parámetro]"
            ],
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "cb63c32e-d51a-4d47-951b-ebeb72456016"
          },
          {
            "name": "SalesCost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR _Units = SELECTEDVALUE(Cambiador_unidades[Unidades], \"Sin resumir\")",
              "RETURN",
              "SWITCH(_Units, \"Millones\", 0.000001, \"Miles\", 0.001, 1)",
              "*",
              "SUMX( ",
              "    InternetSales , ",
              "    InternetSales[Unit Cost] * InternetSales[Quantity] ",
              ")"
            ],
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "8d32334b-63a2-4232-afb0-6699700ee816"
          },
          {
            "name": "% Margin",
            "description": "Margen de ventas",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "DIVIDE (",
              "    SUM(InternetSales[Net Price]) ,",
              "    SUM(InternetSales[Unit Cost])",
              "    , 0",
              ")"
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "5b849163-0660-4bfa-a8ac-e1de9609f365"
          },
          {
            "name": "Cantidad Ventas",
            "displayFolder": "*Medidas",
            "expression": "COUNTROWS(InternetSales)",
            "formatString": "0",
            "lineageTag": "87fc8aba-25e8-405f-a931-8b3b7b66b738"
          },
          {
            "name": "Color Margin",
            "description": "Medida para formato condicional del margen",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "IF ( ",
              "    [% Margin] < 1.5 , \"#fc4103\", -- RED",
              "    IF (",
              "        [% Margin] < 2.5 , \"#fcf403\", -- YELLOW",
              "        \"#03fc4a\" -- GREEN",
              "    )",
              ")"
            ],
            "lineageTag": "34fdc67f-d805-4003-b429-45171e9c2f98"
          },
          {
            "name": "$ ALL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "description": "Medida de ventas para todas ellas en la tabla",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "CALCULATE(",
              "    [SalesAmount],",
              "    ALL(InternetSales[Order Date])",
              ")"
            ],
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "c5c96f08-80ba-4000-8b32-cdbb629c47a6"
          },
          {
            "name": "$ ALLSELECTED",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "description": "Medida de ventas para todas ellas en la tabla aceptando filtros externos",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "CALCULATE(",
              "    [SalesAmount],",
              "    ALLSELECTED(InternetSales[Order Date])    ",
              ")"
            ],
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "87028f26-d70d-4dc4-93e5-6df8a134d802"
          },
          {
            "name": "$ ALLEXCEPT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "description": "Medida de ventas para todas ellas con excepciones en la tabla",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "CALCULATE(",
              "    [SalesAmount],",
              "    ALLEXCEPT(",
              "        InternetSales, ",
              "        InternetSales[Order Date]",
              "))"
            ],
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "b9c2321c-4462-491e-8742-9bf23b4ff97d"
          },
          {
            "name": "Monto Venta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "description": "Modificacion a manopla para probar merge.",
            "displayFolder": "*Medidas",
            "expression": "SUMX(InternetSales, InternetSales[Net Price] * InternetSales[Quantity])",
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "dce18177-1483-45c4-8ede-1e2bf133fd5c"
          },
          {
            "name": "Rentabilidad",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": "[Monto Venta] - [SalesCost]",
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "43bd3e80-ecab-4865-baf5-9ae639a69b75"
          },
          {
            "name": "Venta promedio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "DIVIDE(",
              "    [Monto Venta] ,",
              "    [Cantidad Ventas]",
              ")"
            ],
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "ec8ec644-ff73-4573-9353-9e47df903e88"
          },
          {
            "name": "Proyeccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR __prom_mensual = ",
              "DIVIDE(",
              "    CALCULATE(SUM(InternetSales[Quantity]), ALLEXCEPT(TablaFecha, TablaFecha[Año]))",
              "    , 12",
              ")",
              "VAR __cantidad_actual = SUM(InternetSales[Quantity])",
              "RETURN",
              "__cantidad_actual + ABS(__cantidad_actual - __prom_mensual)"
            ],
            "lineageTag": "80735237-a50d-48e0-899b-185d5f6feabd"
          },
          {
            "name": "Total Proyeccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "SUMX(",
              "    ADDCOLUMNS(",
              "        SUMMARIZE(",
              "            TablaFecha, TablaFecha[Año], TablaFecha[Mes]",
              "        )",
              "        , \"@Proyeccion\", [Proyeccion]",
              "    )",
              "    , [@Proyeccion]",
              ")",
              "        "
            ],
            "lineageTag": "86949cdb-bcb0-4fa7-a2b1-02af5a61fc3e"
          },
          {
            "name": "Anterior",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR __rowdate = SELECTEDVALUE(TablaFecha[Fecha])",
              "VAR __last = ",
              "MAXX(",
              "    FILTER(",
              "        ALL(TablaFecha[Fecha]), AND([Cantidad Ventas]<>BLANK(), TablaFecha[Fecha] < __rowdate)",
              "    )",
              "    , TablaFecha[Fecha]",
              ")",
              "VAR __lastvalue = ",
              "CALCULATE(",
              "    [Cantidad Ventas], TablaFecha[Fecha] = __last",
              ")",
              "RETURN",
              "IF (__lastvalue < [Cantidad Ventas], 1, 0)",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8c992e10-829f-4944-bce5-70053739137d"
          },
          {
            "name": "Number Consecutive Days",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR __selecteddate =",
              "    SELECTEDVALUE ( TablaFecha[Fecha] )",
              "VAR __lastnotworkeddate =",
              "    CALCULATE (",
              "        MAXX (",
              "            FILTER ( TablaFecha,  CALCULATE ( [Anterior] ) = 0  ),",
              "            TablaFecha[Fecha]",
              "        ),",
              "    TablaFecha[Fecha] < __selecteddate",
              ")",
              "VAR differ =",
              "    DATEDIFF ( [Fecha Anterior sin Crecimiento], __selecteddate, DAY )",
              "RETURN",
              "IF ( [Crecimiento # ventas] > 0, IF ( differ > 0, differ ) )"
            ],
            "formatString": "0",
            "lineageTag": "7e91c75b-40f8-4255-98c6-1b5cf3e9b334"
          },
          {
            "name": "Fecha Anterior sin Crecimiento",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "",
              "VAR __rowdate = SELECTEDVALUE(TablaFecha[Fecha])",
              "VAR __last = ",
              "MAXX(",
              "    FILTER(",
              "        ALL(TablaFecha[Fecha])",
              "        , AND(",
              "            OR([Crecimiento # ventas]<0 , [Crecimiento # ventas] = BLANK())",
              "            , TablaFecha[Fecha] < __rowdate",
              "        )",
              "    )",
              "    , TablaFecha[Fecha]",
              ")",
              "RETURN",
              "__last"
            ],
            "formatString": "General Date",
            "lineageTag": "2a685266-58b9-47a0-a674-9d8139c3e069"
          },
          {
            "name": "Cantidad Ventas LD",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "CALCULATE(",
              "    [Cantidad Ventas]",
              "    , PREVIOUSDAY(TablaFecha[Fecha])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "101fdfeb-399f-4df9-b8aa-1794073935fc"
          },
          {
            "name": "Crecimiento # ventas",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "DIVIDE(",
              "    [Cantidad Ventas]-[Cantidad Ventas LD]",
              "    , [Cantidad Ventas LD]",
              ")"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "3b410c56-255e-48e7-8d5f-1290b956aced"
          },
          {
            "name": "Number Consecutive Months",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR __selecteddate =",
              "    SELECTEDVALUE ( TablaFecha[StartOfMonth] )",
              "VAR __crecimientomensual =",
              "DIVIDE(",
              "    [Cantidad Ventas]-[Cantidad Ventas LM]",
              "    , [Cantidad Ventas LM]",
              ")",
              "VAR __lastnotworkeddate =",
              "MAXX(",
              "    FILTER(",
              "        ALL(TablaFecha)",
              "        , AND(",
              "            OR(CALCULATE(__crecimientomensual)<0 , CALCULATE(__crecimientomensual) = BLANK())",
              "            , TablaFecha[StartOfMonth] < __selecteddate",
              "        )",
              "    )",
              "    , TablaFecha[StartOfMonth]",
              ")",
              "VAR differ =",
              "    DATEDIFF ( __lastnotworkeddate, __selecteddate, MONTH )",
              "    ",
              "",
              "RETURN",
              "--IF ( CALCULATE(__crecimientomensual) > 0, IF ( __differ > 0, __differ ) )",
              "__lastnotworkeddate",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "d00d9832-29f5-4f67-bc56-84b5685b58b4"
          },
          {
            "name": "Cantidad Ventas LM",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "CALCULATE(",
              "    [Cantidad Ventas]",
              "    , PREVIOUSMONTH(TablaFecha[Fecha])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d04c4f9f-f3d7-486c-b7db-e4c4c5567e87"
          },
          {
            "name": "Proyeccion Sin Variables",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "SUM(InternetSales[Quantity]) + ",
              "ABS (",
              "    SUM(InternetSales[Quantity]) -",
              "    DIVIDE(",
              "        CALCULATE(SUM(InternetSales[Quantity]), ALLEXCEPT(TablaFecha, TablaFecha[Año]))",
              "        , 12",
              "    )",
              ")"
            ],
            "lineageTag": "a7d4eb66-e407-4f0b-8d31-db785f4e6117"
          },
          {
            "name": "Proyeccion con Variables",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "VAR __cantidad = SUM(InternetSales[Quantity])",
              "RETURN",
              "__cantidad + ",
              "ABS (",
              "    __cantidad -",
              "    DIVIDE(",
              "        CALCULATE(__cantidad, ALLEXCEPT(TablaFecha, TablaFecha[Año]))",
              "        , 12",
              "    )",
              ")"
            ],
            "lineageTag": "80c5d34e-8524-40f8-8106-e1b86698b862"
          },
          {
            "name": "IsBlank Cantidad Ventas",
            "displayFolder": "*Medidas",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([Cantidad Ventas])",
              "    , \"There is no data for the filter selection\"",
              "    , \"\"",
              ")"
            ],
            "lineageTag": "ff95283b-2e7a-43ec-ab88-4b30c257a6aa"
          }
        ],
        "partitions": [
          {
            "name": "InternetSales-89eb3506-04f7-469b-8e0b-e0b6248b370d",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/InternetSales.csv\"),[Delimiter=\";\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    //Remove time custom format from text",
                "    #\"Extracted Text (Date) Before Delimiter\" = Table.TransformColumns(#\"Encabezados promovidos\", {{\"Order Date\", each Text.BeforeDelimiter(_, \" \"), type text},{\"Due Date\", each Text.BeforeDelimiter(_, \" \"), type text},{\"Delivery Date\", each Text.BeforeDelimiter(_, \" \"), type text}}),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Extracted Text (Date) Before Delimiter\",{{\"StoreKey\", Int64.Type}, {\"ProductKey\", Int64.Type}, {\"CustomerKey\", Int64.Type}, {\"Quantity\", Int64.Type}, {\"Unit Price\", Currency.Type}, {\"Unit Discount\", Currency.Type}, {\"Unit Cost\", Currency.Type}, {\"Net Price\", Currency.Type}, {\"Order Date\", type date}, {\"Due Date\", type date}, {\"Delivery Date\", type date}}),",
                "    //Filter OrderDate with parameters to reduce rows and work with sample",
                "    #\"Filtered Rows By OrderDate > Param\" = Table.SelectRows(#\"Tipo cambiado\", each [Order Date] > ReduccionFilas)",
                "in",
                "    #\"Filtered Rows By OrderDate > Param\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parámetro",
        "columns": [
          {
            "name": "Parámetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f565a3bc-8509-4fd0-8353-85a2a104fb94",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2fc67b2f-9e38-4396-8dbb-855d99ee780b",
        "measures": [
          {
            "name": "Valor Parámetro",
            "expression": "SELECTEDVALUE('Parámetro'[Parámetro], 1)",
            "lineageTag": "db49b59e-2578-4a06-9242-aa8374e8b795"
          }
        ],
        "partitions": [
          {
            "name": "Parámetro-499cce18-b44a-420d-88a8-1e044964d636",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 1.3, 0.1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PresupuestoCompras",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74dfb98e-e796-4b00-98a1-3cbf316d49ec",
            "sourceColumn": "Area",
            "summarizeBy": "none"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9a9646d-e7fc-40a2-ad77-4977d947d1f4",
            "sourceColumn": "Año",
            "summarizeBy": "none"
          },
          {
            "name": "Gerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50eb68ae-0d1a-4cb9-a77d-bd0156ed18e2",
            "sourceColumn": "Gerente",
            "summarizeBy": "none"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8da7350-122a-45a0-9cc2-00f082fe25e5",
            "sourceColumn": "Mes",
            "summarizeBy": "none"
          },
          {
            "name": "Monto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "671cc58f-cf9b-453e-8157-d841829e28d8",
            "sourceColumn": "Monto",
            "summarizeBy": "sum"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa01e918-470c-4b60-ab2d-a128f1be2c11",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a52f797d-9d31-4bf9-8bbf-f2f27c681161",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d3119299-53de-4767-bdac-0dc640b980cd",
        "partitions": [
          {
            "name": "PresupuestoCompras-63e1f5a6-328c-4602-96e0-8d203decfec9",
            "mode": "import",
            "queryGroup": "Facts",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/Budget2019-compras.xlsx\"), null, true),",
                "    Tabla1_Table = Origen{[Item=\"Tabla1\",Kind=\"Table\"]}[Data],",
                "    //Quitar pivoteo de columnas de fecha",
                "    #\"Anulación de dinamización de periodos\" = Table.UnpivotOtherColumns(Tabla1_Table, {\"Region\", \"Area\", \"Gerente\"}, \"Periodo\", \"Monto\"),",
                "    //Duplicar Periodo para no perderlo al dividirlo",
                "    #\"Columna duplicada (Periodo)\" = Table.DuplicateColumn(#\"Anulación de dinamización de periodos\", \"Periodo\", \"Periodo - Copia\"),",
                "    //Dividir copia de periodo en año y mes",
                "    #\"Dividir periodo por guion medio\" = Table.SplitColumn(#\"Columna duplicada (Periodo)\", \"Periodo - Copia\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"Año\", \"Mes\"}),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Dividir periodo por guion medio\",{{\"Region\", type text}, {\"Area\", type text}, {\"Gerente\", type text}, {\"Monto\", type number}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Available Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fb1cf871-644d-4fbb-9699-15be806036d1",
            "sourceColumn": "Available Date",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17262aaf-1f76-4310-b79e-b50fcc6f1f39",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Cantidad Ventas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "COUNTROWS(RELATEDTABLE(InternetSales) )",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "167ea070-5323-40d5-9cb6-acd51394e66a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07683c55-c06d-45a7-9d6b-5b8b50586bae",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70d49f19-b900-4f29-94ab-b87335ce587c",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "852265ce-122a-49bb-81b8-4b2a21554bc5",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "855cb8dc-0d5f-4131-a11d-bd2ec56f8124",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2717ad77-0db2-4565-8476-4b76dc59b9c8",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "1ced00ae-daee-4216-950a-25b990c620f8",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;-\\$#,0.###############;\\$#,0.###############",
            "lineageTag": "9869086b-1854-4fc3-885e-d26db0b6ca72",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7fe3dda2-6711-4209-85bd-99088a2170b6",
        "partitions": [
          {
            "name": "Product-4d66dae4-17df-45f6-85ae-6683c7644026",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/Product.csv\"),[Delimiter=\";\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"ProductKey\", Int64.Type}, {\"Product Name\", type text}, {\"ProductSubcategoryKey\", Int64.Type}, {\"Manufacturer\", type text}, {\"Brand\", type text}, {\"Color\", type text}, {\"Unit Cost\", Currency.Type}, {\"Unit Price\", Currency.Type}, {\"Available Date\", type date}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "172ef48c-69a3-4193-b02d-266b8e7df68f",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "759f6fdd-640e-4b86-871b-5a2c814142f9",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9b5039a9-cbc1-43bb-ac8f-611bf6229963",
        "partitions": [
          {
            "name": "ProductCategory-f16cf301-f8b5-40cf-a124-793f54b7d3c3",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/ProductCategory.csv\"),[Delimiter=\";\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"ProductCategoryKey\", Int64.Type}, {\"Category\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductSubCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03354220-7c64-45a8-8c73-2cbb07fb7c07",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd340247-3662-42e8-b978-4e8c26babc2d",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34b181d0-a9b3-4633-8658-cc7fe0d2c30d",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bafb574d-8db7-49f6-a6c1-e2f7d7ba4a76",
        "partitions": [
          {
            "name": "ProductSubCategory-0826693d-13e2-49d7-ac9c-55c9564a99d6",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/ProductSubCategory.csv\"),[Delimiter=\";\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Encabezados promovidos\",{{\"ProductSubcategoryKey\", Int64.Type}, {\"Subcategory\", type text}, {\"ProductCategoryKey\", Int64.Type}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Stores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40aec55d-77e7-48fe-ac4b-6e3d0534a96c",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90970523-b955-4c29-a684-3b8b7d97b74e",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "CountryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "b73739dc-9de9-4c23-94a8-065329cc1b42",
            "sourceColumn": "CountryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "Employees",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6dd55b70-2435-4eec-8d0f-fc1903f2046f",
            "sourceColumn": "Employees",
            "summarizeBy": "sum"
          },
          {
            "name": "Last Remodel Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "075e29cd-65f7-47f2-8af4-a8bcece20551",
            "sourceColumn": "Last Remodel Date",
            "summarizeBy": "none"
          },
          {
            "name": "Selling Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a64c35ac-1c6e-4a92-ac03-3233f8599b55",
            "sourceColumn": "Selling Area",
            "summarizeBy": "sum"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "e5badc3d-7751-48d5-90d9-d4d9058948a3",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Store Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9977edf3-329f-47c4-be78-5b91a5f58e73",
            "sourceColumn": "Store Name",
            "summarizeBy": "none"
          },
          {
            "name": "Store Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39b442d0-b2da-43c4-8158-dd2cf179ef42",
            "sourceColumn": "Store Type",
            "summarizeBy": "none"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d1b008a-d438-45cc-b09e-96e26eb75683",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a544a520-b199-4cf7-bff8-2919b1680eda",
        "measures": [
          {
            "name": "Mensaje alerta",
            "expression": [
              "",
              "IF (",
              "    COUNTROWS(VALUES(Stores[CountryRegion])) > 1,",
              "    \"Ha seleccionado más de un país. Asegurese de tener seleccionado monto en USD.\",",
              "    \"\"    ",
              ")"
            ],
            "lineageTag": "52566f7c-229b-415a-b08b-5d15388bc0c9"
          },
          {
            "name": "One Country in Store",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(Stores[CountryRegion])",
              "    , 1",
              "    , 0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5e4275dd-4e45-4d8f-8b61-92a2168dfcdd"
          },
          {
            "name": "One Country in Store msg",
            "expression": [
              "",
              "IF (",
              "    HASONEVALUE(Stores[CountryRegion])",
              "    , \"\"",
              "    , \"Please pick only one country to analyze the ranking\"",
              ")"
            ],
            "lineageTag": "0fa30b05-9776-4998-86fc-aa8377dfea95"
          }
        ],
        "partitions": [
          {
            "name": "Stores-8470d9bd-a0aa-41a1-8e14-2e92a0e28cbd",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/ibarrau/PowerBi-code/master/DatosPrueba/Stores.csv\"),[Delimiter=\";\", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Encabezados promovidos\",{{\"StoreId\", \"StoreKey\"}}),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"StoreKey\", Int64.Type}, {\"Store Type\", type text}, {\"Store Name\", type text}, {\"Continent\", type text}, {\"City\", type text}, {\"State\", type text}, {\"CountryRegion\", type text}, {\"Employees\", Int64.Type}, {\"Selling Area\", Int64.Type}, {\"Last Remodel Date\", type date}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TablaFecha",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa1bd705-3216-4622-99a8-fd2b0bb3d9d3",
            "sourceColumn": "Año",
            "summarizeBy": "sum"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abbd8e6e-fc9c-4cbb-8ce5-92ad0454b014",
            "sourceColumn": "Dia",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "52d7c539-b7c8-4a02-a475-d3aa670fd578",
            "sourceColumn": "Fecha",
            "summarizeBy": "none"
          },
          {
            "name": "IdMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b91e77a9-b891-4aeb-b534-9e355d6b9a92",
            "sourceColumn": "IdMes",
            "summarizeBy": "sum"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "593422ca-eb57-4216-b67b-5f6ca49405be",
            "sortByColumn": "IdMes",
            "sourceColumn": "Mes",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85446074-523c-4795-a150-0686017ba196",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "StartOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0b1f31c8-2786-4135-bfd8-48f4bdd2e45d",
            "sourceColumn": "StartOfMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Ultimo 4 quarters",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    DATEDIFF(TablaFecha[Fecha], today(), QUARTER) <= 4,",
              "    \"Last 4 quarters\",",
              "    \"From last 4 quarter to firt date\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f97c2ed4-7ce2-4963-9f28-d33cb278eff3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "60e6a4b1-cc12-4127-8614-ad83bcaaaeab",
        "partitions": [
          {
            "name": "TablaFecha-dd203e0d-38fd-4afd-a122-24b4e883d48d",
            "mode": "import",
            "queryGroup": "Dimensions",
            "source": {
              "expression": [
                "let",
                "    Origen = let",
                "//Capture the date range from the parameters",
                "    StartDate = #date(2006, 1, 1),",
                "    EndDate = #date(2009, 12, 31),",
                "//Get the number of dates that will be required for the table",
                "    GetDateCount = Duration.Days(EndDate - StartDate),",
                "//Take the count of dates and turn it into a list of dates",
                "    GetDateList = List.Dates(StartDate, GetDateCount, ",
                "    #duration(1,0,0,0)),",
                "//Convert the list into a table",
                "    DateListToTable = Table.FromList(GetDateList, ",
                "    Splitter.SplitByNothing(), {\"Fecha\"}, null, ExtraValues.Error),",
                "//Add Year Column",
                "    YearNumber = Table.AddColumn(DateListToTable, \"Año\", ",
                "    each Date.Year([Fecha]), Int32.Type),",
                "//Add Month Number Column",
                "    MonthNumber = Table.AddColumn(YearNumber , \"IdMes\", ",
                "    each Date.Month([Fecha]), Int32.Type),",
                "//Add Month Name Column",
                "    MonthName = Table.AddColumn(MonthNumber , \"Mes\", ",
                "    each Date.ToText([Fecha],\"MMMM\", \"es-es\"), type text),",
                "//Add Day Number Column",
                "    DayNumber  = Table.AddColumn(MonthName , \"Dia\", ",
                "    each Date.Day([Fecha]), Int32.Type),",
                "//Add Q",
                "    Quarter  = Table.AddColumn(DayNumber , \"Quarter\", ",
                "    each Text.From([Año])&\"Q\"& Text.From(Date.QuarterOfYear([Fecha])), type text),",
                "//Start of week",
                "    StartOfMonth = Table.AddColumn(Quarter, \"StartOfMonth\",",
                "    each Date.StartOfMonth([Fecha]), type date)",
                "in",
                "    StartOfMonth,",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Fecha\", type date}, {\"Quarter\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TableCountConsecutive",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90398e7a-a81f-4c54-94cb-83323a9b3d4c",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Bar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c9bf20c-18e3-4098-8fb1-0f605a4a5ec6",
            "sourceColumn": "Bar",
            "summarizeBy": "none"
          },
          {
            "name": "Fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "70f8bebe-dc96-4840-977e-a1a96075631b",
            "sourceColumn": "Fecha",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "44cdf776-9da1-4c17-8966-edbc92509d37",
        "measures": [
          {
            "name": "Anterior2",
            "expression": [
              "",
              "VAR __rowdate = SELECTEDVALUE(TablaFecha[Fecha])",
              "VAR __last = ",
              "MAXX(",
              "    FILTER(",
              "        ALL(TablaFecha[Fecha]), AND([Sumada]<>BLANK(), TablaFecha[Fecha] < __rowdate)",
              "    )",
              "    , TablaFecha[Fecha]",
              ")",
              "VAR __lastvalue = ",
              "CALCULATE(",
              "    [Sumada], TablaFecha[Fecha] = __last",
              ")",
              "RETURN",
              "IF (__lastvalue < [Sumada], 1, 0)",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "53347754-9c08-46bb-88cb-05db01b17d1c"
          },
          {
            "name": "Sumada",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('TableCountConsecutive'[Amount])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "15524a4a-2aaf-4a92-8afa-7642ac31d905"
          },
          {
            "name": "Consecutivos",
            "expression": [
              "",
              "VAR __selecteddate =",
              "SELECTEDVALUE ( TablaFecha[Fecha] )",
              "VAR __lastnotworkeddate =",
              "CALCULATE (",
              "    MAXX (",
              "        --FILTER ( TablaFecha, ISBLANK ( CALCULATE ( [Count of Sales] ) ) ),",
              "        FILTER ( TablaFecha,  CALCULATE ( [Anterior2] ) = 0 && [Sumada]<>BLANK() ),",
              "        TablaFecha[Fecha]",
              "    ),",
              "    TablaFecha[Fecha] < __selecteddate",
              ")",
              "VAR diff =",
              "    DATEDIFF ( __lastnotworkeddate, __selecteddate, MONTH )",
              "RETURN",
              "IF ( [Anterior2] > 0, IF ( diff > 1, diff ) )"
            ],
            "formatString": "0",
            "lineageTag": "8a1e306e-d4cd-446f-8f5a-ca02789aed11"
          },
          {
            "name": "Consecutivos_v2",
            "expression": [
              "",
              "VAR __selecteddate =",
              "SELECTEDVALUE ( TablaFecha[Fecha] )",
              "VAR __firstcontextdate = ",
              "MINX ( ",
              "    ALLSELECTED(TablaFecha[Fecha]),",
              "    TablaFecha[Fecha]",
              ")",
              "VAR __lastnotworkeddate =",
              "    MAXX (",
              "        FILTER ( ALLSELECTED(TablaFecha),  ",
              "            [Anterior2]  = 0 && [Sumada]<>BLANK() && TablaFecha[Fecha] < __selecteddate ",
              "        ),",
              "        TablaFecha[Fecha]",
              "    )",
              "VAR diff =",
              "    IF(ISBLANK(__lastnotworkeddate)",
              "        , DATEDIFF (__firstcontextdate, __selecteddate, MONTH ) +1",
              "        , DATEDIFF (__lastnotworkeddate, __selecteddate, MONTH )",
              "    )",
              "RETURN",
              "IF ( [Anterior2] > 0, IF ( diff > 1, diff ) )"
            ],
            "formatString": "0",
            "lineageTag": "6f510f0e-b2e9-4845-8800-0743abedd5ca"
          }
        ],
        "partitions": [
          {
            "name": "TableCountConsecutive-3a5960f6-2928-4ff6-ac54-c19adc94c001",
            "mode": "import",
            "queryGroup": "Auxiliars",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"fdA9DoAgDIDRuzCTSPnnBK7uxoHBGBcZ9P7RNMEIFgaml7Tlm2c2xStu6dgj48w/DwYYpBCOLbxEhyhptIiKRoOoaZSIhkaFaGnUiK53re8dFHo7QfTmwqfRmNK5vh8hQNXhMpg6WjlKt0aZP4Q6VAbn60rlEt9aElr3fstkgbLKcgM=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Bar = _t, Amount = _t, Fecha = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Bar\", type text}, {\"Amount\", Int64.Type}, {\"Fecha\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TableRLS",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f274cc1-7b66-4ec7-a77e-7de0120a42f0",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Mail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a7daa0f-5135-4388-afc4-05921d441a47",
            "sourceColumn": "Mail",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a8ef7cc1-6a05-438f-ad0b-ff209fc144cd",
        "partitions": [
          {
            "name": "TableRLS-483206e3-b913-4235-8899-4a19ff959d30",
            "mode": "import",
            "queryGroup": "Auxiliars",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WKkgsynbISUxJLEksT03SS87P1UssUtJRcs7IzEtUitWJVspKzCOgID8vsRibEvfUotzEvEqoogysxoTmZZakpigElySWpBaDVaYmFpcQMg2XGqijYgE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Mail = _t, Country = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Mail\", type text}, {\"Country\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TableTypes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Binary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e7cda3b-1ee1-4f1a-ad7e-7540de58877d",
            "sourceColumn": "Binary",
            "summarizeBy": "sum"
          },
          {
            "name": "Bool",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "1b8d2548-6de0-4fc6-a80a-0f41e29e10f0",
            "sourceColumn": "Bool",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "93aa8a5c-2225-41e5-9e2a-eb5dfad2fa00",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "67319440-a6b9-4d13-bb62-42b1df1a50af",
            "sourceColumn": "DateTime",
            "summarizeBy": "none"
          },
          {
            "name": "Decimal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6703bba1-808b-40cf-b2ad-944cfa7f0fad",
            "sourceColumn": "Decimal",
            "summarizeBy": "sum"
          },
          {
            "name": "Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5cb375bf-97ac-489b-9bd7-e9935844c11b",
            "sourceColumn": "Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "FixedDecimal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-AR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$\\ #,0.###############;-\\$\\ #,0.###############;\\$\\ #,0.###############",
            "lineageTag": "0e51bb8b-fa17-4539-883a-6c01abf353ea",
            "sourceColumn": "FixedDecimal",
            "summarizeBy": "sum"
          },
          {
            "name": "Int",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e615289-e020-436a-bd7b-d463a151c264",
            "sourceColumn": "Int",
            "summarizeBy": "sum"
          },
          {
            "name": "Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c8b64cf-bcf0-4a1b-a8a8-a266fc696924",
            "sourceColumn": "Percentage",
            "summarizeBy": "sum"
          },
          {
            "name": "Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc5d4d34-3ab9-4aa0-8b59-040bb67280c3",
            "sourceColumn": "Text",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "9647dab1-7634-458f-859a-af8690001bc3",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "TimeZone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "74598426-c91b-4a8c-8aa4-17a9acedf3e4",
            "sourceColumn": "TimeZone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9592af2d-59c3-4063-b81d-c39ae2e9a071",
        "partitions": [
          {
            "name": "TableTypes-afeda72c-1623-42f1-946c-27b986624252",
            "mode": "import",
            "queryGroup": "Auxiliars",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlDSUQopKk0FUoYgrGNkDKGAZGJxCpA0MNQHIiMDIwMUjoKBoZWBARCBReFMYxNTkICOsQkO1bE60WCb3BJzikG2gpQbG+kYGpmagi02A5KF5SAZAyN9IIJZDOcoGBghLDZFstgYbDHY/VgtjgUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Binary = _t, Bool = _t, Int = _t, Decimal = _t, FixedDecimal = _t, Text = _t, Date = _t, DateTime = _t, Time = _t, Duration = _t, Percentage = _t, TimeZone = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Binary\", Int64.Type}, {\"Bool\", type logical}, {\"Int\", Int64.Type}, {\"Decimal\", type number}, {\"FixedDecimal\", Currency.Type}, {\"Text\", type text}, {\"Date\", type date}, {\"DateTime\", type datetime}, {\"Time\", type time}, {\"Duration\", type duration}, {\"Percentage\", Percentage.Type}, {\"TimeZone\", type datetimezone}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TooltipDocs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8cbbc13-49bb-44c8-9d29-a21811c40394",
            "sourceColumn": "Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "f238152b-6a57-4cb7-ba18-ea5272dcbc92",
            "sourceColumn": "Image",
            "summarizeBy": "none"
          },
          {
            "name": "URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "dfe2aec5-4836-41af-b5d5-453bd40f1fc4",
            "sourceColumn": "URL",
            "summarizeBy": "none"
          },
          {
            "name": "Visual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eed20403-8cb4-4f75-9028-f306654d3950",
            "sourceColumn": "Visual",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8625dcee-5ca0-4d5f-b1c8-698344f197a4",
        "measures": [
          {
            "name": "Transparente",
            "expression": "\"rgba(0,0,0,0)\"",
            "lineageTag": "d5db4a34-2600-46ac-9a73-b14f5bfb6900"
          },
          {
            "name": "Base 64 render",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "\"<img src='\" & MIN(TooltipDocs[Image]) & \"'/>\""
            ],
            "lineageTag": "ffb9ffa8-bf81-45af-be3e-2f86e74137f1"
          }
        ],
        "partitions": [
          {
            "name": "TooltipDocs-1ce1a0b4-1c71-43a8-afcd-331719690bc9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"7L3JsvM6li72Kn9URM3KYUpsZY/AvqfYSuSNO2An9r1IinybegCPPPM0X8zA/s/J\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Visual = _t, Desc = _t, Image = _t, URL = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Visual\", type text}, {\"Desc\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UserByPage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PagePermission",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f544b279-d2f0-4abe-926f-6f028e369d84",
            "sourceColumn": "PagePermission",
            "summarizeBy": "none"
          },
          {
            "name": "UserConnected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "731a958d-04c1-4339-ac5e-9988458ba5a7",
            "sourceColumn": "UserConnected",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c6245d0d-567b-4be4-a761-26e99b134eca",
        "measures": [
          {
            "name": "Nav_Switcher",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"Switcher\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"Switcher\", \"Denegado\")"
            ],
            "lineageTag": "35997b12-3eb7-450a-b4b5-b0d7ef8d0015"
          },
          {
            "name": "Nav_Navegacion",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"Navegacion\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"Navegacion\", \"Denegado\")"
            ],
            "lineageTag": "4b5ecd69-be50-4a03-923a-2c930d4529e6"
          },
          {
            "name": "Nav_Parameter",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"WhatIfParameters\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"WhatIfParameters\", \"Denegado\")"
            ],
            "lineageTag": "10b4cb21-23d0-487e-a0b8-04fc5294475b"
          },
          {
            "name": "Nav_Format",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"FormatPart2\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"FormatPart2\", \"Denegado\")"
            ],
            "lineageTag": "ddd85f77-62ec-4eb9-8f59-365c441279df"
          },
          {
            "name": "Nav_All",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"ALL vs\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"ALL vs\", \"Denegado\")"
            ],
            "lineageTag": "257dbc57-c50b-47fe-bf2c-449d8853e5f1"
          },
          {
            "name": "Nav_Alert",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"AlertMessage\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"AlertMessage\", \"Denegado\")"
            ],
            "lineageTag": "6df67568-60e1-4663-9582-7709313db269"
          },
          {
            "name": "Nav_Custom",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"Custom visuals\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"Custom visuals\", \"Denegado\")"
            ],
            "lineageTag": "df7c949b-c700-495b-b887-1ddbc887b73e"
          },
          {
            "name": "Nav_ErrorTotals",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"Error in Totals\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"Error in Totals\", \"Denegado\")"
            ],
            "lineageTag": "b9024605-872e-46be-bd14-c0142dd830b5"
          },
          {
            "name": "Nav_PowerPointTemplate",
            "expression": [
              "",
              "VAR __nav = OR( ",
              "    \"PowerPointTemplate\" IN VALUES (UserByPage[PagePermission])",
              "    , \"Todo\" IN VALUES (UserByPage[PagePermission])",
              ")",
              "RETURN",
              "IF ( __nav, \"PowerPointTemplate\", \"Denegado\")"
            ],
            "lineageTag": "dd29f547-e72e-4c3f-bff5-a55143289a1a"
          }
        ],
        "partitions": [
          {
            "name": "UserByPage-186ad230-dd6a-45ac-8e26-b42865cde57a",
            "mode": "import",
            "queryGroup": "Auxiliars",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jcyxCsIwFEbhVwmZSwefwA4KDopgoUPp8De5toEkF24vrY+v6FqI+3dO39vgyMWQRpJjhIdio7F2nGqIrexjC+pmEjtUJXrDShNc4PwH7mbo5XmHIJGSLN/E45WQ9/iZJUE/XA8F2cRo1tKuiSR6pWXBRAV6EmExIZuWFfE3hk9hF7fs2Q7DGw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [UserConnected = _t, PagePermission = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"UserConnected\", type text}, {\"PagePermission\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}