name: Process Reports and Models

on:
  push:
    paths:
      - 'PowerBi Reports/Deploy Pruebas/**'  # Trigger only when there's a change in this folder

jobs:
  process_changes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install the necessary Python package from PyPI
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplepbi 

      # Step 4: Get list of changed folders ending with .report or .semanticmodel
      - name: Get changed folders
        id: detect_changes
        run: |
          # Define the folder to check for changes
          target_folder="PowerBi Reports/Deploy Pruebas/"
          
          # Ensure we're comparing against the previous commit (use HEAD and HEAD^)
          # changed_folders=$(git diff --name-only HEAD^..HEAD -- "$target_folder" | grep -E "/.*\.(Report|SemanticModel)/" | cut -d/ -f1-2 | sort | uniq)
          changed_folders=$(git diff --name-only HEAD^..HEAD -- "$target_folder" | \
            sed 's|/[^/]*$||' | sort | uniq)

          # Save changed folders to output for later use
          # echo "changed_folders=$changed_folders" >> $GITHUB_ENV
          # echo "changed_folders=$changed_folders" | sed 's/ /\\n/g' >> $GITHUB_ENV
          
          changed_folders=$(echo "$changed_folders" | tr '\n' ',')
          # Remove trailing comma if it exists
          changed_folders="${changed_folders%,}"
          echo "changed_folders=$changed_folders" >> $GITHUB_ENV
          echo "Changed folders: $changed_folders"

      # Step 5: Run the Python script with the list of changed folders and secret key
      - name: Run Python script
        run: python deploy.py "d453a221-6f9c-40e3-a7ef-346e068ea8dc" ${{ secrets.TENANT_ID }} ${{ secrets.APP_ID }} ${{ secrets.SECRET_KEY }} ${{ env.changed_folders }} 

